recorder:
  purge_keep_days: 30
  db_url: postgresql://***@192.168.66.30:5432/homeass
  exclude:
    entity_globs:
      - sensor.sun*
      - weather.*
    entities:
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sun.sun # Don't record sun data

# - platform: sql
sql:
  - name: psql_size
    #scan_interval: 10
    unique_id: psql_size
    query: "SELECT (pg_database_size('homeass')/1024/1024) as db_size;"
    column: "db_size"
    unit_of_measurement: MB
